// ACTION STATUS
export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const MAKE_API_REQUEST = 'MAKE_API_REQUEST';

export const SHOW_SUCCESS_TOAST = 'SHOW_SUCCESS_TOAST';
export const SHOW_FAILURE_TOAST = 'SHOW_FAILURE_TOAST';

// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// SELECT OPTIONS
export const GET_SELECT_OPTIONS = 'GET_SELECT_OPTIONS';

// QUESTION LIST
export const GET_QUESTION_LIST = 'GET_QUESTION_LIST';

export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';